### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'read'.

### ISSUE THREAD

**Issue by cupen** [ajalt/fuckitpy#19]
Windows 7 
Python 2.7.8 
fuckit 4.8.0 (installed by `pip2.7 install fuckit` )  

```bash
$ python2.7 webqq.py
Traceback (most recent call last):
  File "webqq.py", line 49, in <module>
    fuckit('config')
  File "d:\Python27\lib\site-packages\fuckit.py", line 119, in __call__
    source = sourcefile.read()
AttributeError: 'NoneType' object has no attribute 'read'
```

**Comment by ajalt** [comment]
This is "fixed" in a966e4.

**Comment by cupen** [comment]
Thanks.  ;D
