### ISSUE TITLE
doesn't fucking put out

### ISSUE THREAD

**Issue by vitiral** [ajalt/fuckitpy#27]
Really disapointed with this module, can't rely on it for fucking with my code at all. It can't even fuck it's own example anymore!

Run example.py and you get this:
```
 fuckit git:(master) ✗ python2 example.py
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    fuckit(fuckit('broke'))
  File "/home/garrett/.local/lib/python2.7/site-packages/fuckit.py", line 118, in __call__
    sourcefile, pathname, _description = imp.find_module(victim)
ImportError: No module named broke
```

Fucking disapointed. Removing "broke" related stuff and python2 works like a charm. However, python3 is a total trainwreck:
```
 fuckit git:(master) ✗ python3 example.py 
Traceback (most recent call last):
  File "example.py", line 11, in <module>
    class BrokenClass(object):
  File "/home/garrett/.local/lib/python3.5/site-packages/fuckit.py", line 172, in __call__
    elif isinstance(victim, (types.ClassType, type)):
AttributeError: module 'types' has no attribute 'ClassType'
```

Python3 had other issues, like that it wouldn't modify the ast tree to skip name errors or zero-division-errors or anything. Seriously, the only thing it seemed to do was call the function multiple times without skipping any errors at all!

Until you can make this put out for all my pythons, I shall not be using it for any of my projects -- it's simply too unreliable.

**Comment by vitiral** [comment]
I take back everything I said, I'm a fucking moron. Godspeed motherfucker.
